BankApi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bankapiapp.urls')),
]

bankapiapp/urls.py
from django.contrib import admin
from django.urls import path
from bankapiapp.views import GetBranchDetails, GetAllBranch

app_name = 'bankapiapp'
urlpatterns = [
    path('branchdetail/', GetBranchDetails.as_view(), name='branchdetail'),
    path('allbranch/', GetAllBranch.as_view(), name='allbranch')
]

bankapiapp/models.py
from django.db import models

# Create your models here.
class BankView(models.Model):
    ifsc = models.CharField(max_length = 11, primary_key=True)
    bank_id = models.IntegerField()
    branch = models.CharField(max_length=74)
    address = models.CharField(max_length=195)
    city = models.CharField(max_length=50)
    district = models.CharField(max_length=50)
    state = models.CharField(max_length=26)
    bank_name = models.CharField(max_length=49)


    class Meta:
        managed = False
        db_table = 'bank_branches'

bankapiapp/views.py
from django.shortcuts import render
from bankapiapp.models import BankView
from bankapiapp.serializer import BankSerializer
from rest_framework.views import APIView
from rest_framework.response import Response
from django.db.models import Q

# Create your views here.
class GetBranchDetails(APIView):
    serializer_class = BankSerializer

    def get(self, request, format=None):
        template_name = 'bankapiapp/branch.html'
        ifsc_code = request.GET.get('txtSearch')
        bank_detail = BankView.objects.filter(ifsc = ifsc_code)
        serializer = BankSerializer(bank_detail, many=True)
        return Response({'data' : serializer.data}, template_name=template_name)

class GetAllBranch(APIView):
    
    serializer_class = BankSerializer

    def get(self, request, format=None):
        template_name = 'bankapiapp/allbranch.html'
        bank_ = request.GET.get('txtbank')
        city_ = request.GET.get('txtcity')
        bank_detail = BankView.objects.filter(Q(bank_name__iexact=bank_) & Q(city__iexact=city_))
        serializer = BankSerializer(bank_detail, many=True)
        # print(bank_detail)
        return Response({'data' : serializer.data}, template_name=template_name)

bankapiapp/templates/bankapiapp/allbranch.html
<!DOCTYPE html>
<html lang="en">
<head>
        {% load rest_framework %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"/>
    <title>All Details</title>
</head>
<body>
        <div class="form-group">
                <a href="{% url 'bankapiapp:branchdetail' %}"> Search Branch Info</a>
        </div>
    <form  method="GET" action="{% url 'bankapiapp:allbranch' %}"> {% csrf_token %}

            <div class="form-group">
                    <label for="usr">Bank Name:</label>
                    <input type="text" class="form-control"  name="txtbank" value="{{ request.GET.txtbank }}">
            </div>
            <div class="form-group">
                    <label for="pwd">City:</label>
                    <input type="text" class="form-control" name="txtcity" value="{{ request.GET.txtcity }}">
            </div>

        
            <div class="form-group">
                    <button class="btn btn-success btn-block" type="submit">
                    <span class="glyphicon glyphicon-search"> </span>
                    </button>
            </div>

        </div>
      </form>

      {% if data  %}
      <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th>ifsc</th> <th>bank_name</th> <th>branch</th> <th>address</th> <th>city</th><th>district</th><th>state</th>
            </tr>
        </thead>
        {% for d in data %}
            <tr>
                <td> {{d.ifsc}} </td>
                <td> {{d.bank_name | upper}} </td>
                <td> {{d.branch | upper}} </td>
                <td> {{d.address | upper}} </td>
                <td> {{d.city | upper}} </td>
                <td> {{d.district | upper}} </td>
                <td> {{d.state | upper}} </td>
            </tr>
        {% endfor %}
    </table>
      {% endif %}

</body>
</html>

bankapiapp/templates/bankapiapp/branch.html
<!DOCTYPE html>
<html lang="en">
<head>
        {% load rest_framework %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"/>
    <title>Branch Details</title>
</head>
<body>
    <div class="form-group">
        <a href="{% url 'bankapiapp:allbranch' %}"> Search Bank Name and City</a>
</div>
    <form  method="GET" action="{% url 'bankapiapp:branchdetail' %}"> {% csrf_token %}
        <div class="row">
          <div class="col-xs-6 col-md-4">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Enter IFSC code"  name="txtSearch" id="txtSearch" value="{{ request.GET.txtSearch }}"/>
              <div class="input-group-btn">
                <button class="btn btn-primary" type="submit">
                  <span class="glyphicon glyphicon-search"> </span>
                </button>
              </div>
            </div>
          </div>
        </div>
      </form>

      {% if data  %}
      <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th>ifsc</th> <th>bank_name</th> <th>branch</th> <th>address</th> <th>city</th><th>district</th><th>state</th>
            </tr>
        </thead>
            <tr>
                <td> {{data.0.ifsc}} </td>
                <td> {{data.0.bank_name | upper}} </td>
                <td> {{data.0.branch | upper}} </td>
                <td> {{data.0.address | upper}} </td>
                <td> {{data.0.city | upper}} </td>
                <td> {{data.0.district | upper}} </td>
                <td> {{data.0.state | upper}} </td>
            </tr>
    </table>
      {% endif %}
</body>
</html>